print('this is the program to create resume')
name=str(input('Enter your name: '))
fname=str(input('''Enter your father's name: '''))
mname=str(input('''Enter your mother's name: '''))
qua=input('your qualifications=')
print('Enter your address below in following format')
hn=input('House no. ')
rn=input('Name of road/locality= ')
ct=input('Name pf city= ')
pn=input('pincode=')
hn2=input('house no of receiver=')
rn2=input('name of road locality of receiver=')
ct2=input('city of receiver=')
pn2=input('pincode of receiver=')
app=input('Enter what post you are applying for=')
dt=input('Enter the date of application in form of (dd mm yyyy)=')
appm=input('Enter whom you are applying to=')
dob=input('Enter your date of birth in format of (DD MM YYYY)=')
sx=input('Enter your sex=')
ms=input('Enter your maritial status(single/married)=')
rf=input('Enter the name of referenced newspaper=')
da=input('when the advertisement published=')
print('')
print('')
print('')
print('')
print('')
print(hn)
print(rn)
print(ct,',',pn)

print(dt)

print (hn2)
print(rn2)
print(ct2,',',pn2)
print ('Dear sir/mam,')
print('subject: Application for the post of',app)
print('')
print('This is the response to your advertisement in',rf,'of',da,'. I have requisite qualification and experience. My resume is enclosed herewith for your kind perusal and consideration. I can assure you that if selected, I shall prove to be great asset to your company.')
print('')
print('Yours Faithfully')
print(name)
print('')
print('NAME:',name)
print('FATHERS NAME:',fname)
print('MOTHERS NAME:',mname)
print('DATE OF BIRTH:',dob)
print('SEX:',sx)
print('MARITIAL STATUS:',ms)
print('PERMANENT ADDRESS:',hn,rn,ct,pn)
print('QUALIFICATIONS:',qua)
